apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: lbs
      protocol: layer2
      addresses:
      - 192.168.86.4/30
